PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX biom_res: <http://www.biom-format.org/resource/>
SELECT ?value 
WHERE { 
?cell biom_res:BIOM_000025 biom_res:BIOM_000036 .
?cell biom_res:BIOM_000026 biom_res:BIOM_000030 .
?cell biom_res:BIOM_000027 ?value  
}